name: Docker Hub Publish

on:
  push:
    branches:
      - main  # or your default branch

jobs:
  build-and-push:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Login to Docker Hub
        uses: docker/login-action@v1
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_PASSWORD }}

      - name: Build and push Docker image
        run: |
          docker build -t punkyard/bolt.diy:0.0.5 .
          docker push punkyard/bolt.diy:0.0.5
